### ISSUE TITLE
Script requires an extra update

### ISSUE THREAD

**Issue by TrainerFromHoenn** [Romulion/LMD_Animation_Loader#3]
I tried installing this script on Blender 2.92 and got this error
![error](https://user-images.githubusercontent.com/26364966/112833833-8faeef80-9097-11eb-81ee-e1a2496b00fe.PNG)
So after this i tried reversing Blender to 2.83.13 and still got the same error.
.lmd models load fine, but not .lmd animations.

**Comment by Romulion** [comment]
Just change in file head
	

> "blender": (2, **79**, 0),

to
	

> "blender": (2, **80**, 0),

Works on Blender 2.92

**Comment by Romulion** [comment]
Add multiple version support to script
